# id 生成器机器唯一 id
workerId: 0
# token 相关参数
# 身份认证 token 的有效期: 30 天
authTokenDuration: 2592000
appId: tokenId
appKey: tokenKey
server:
  session-timeout: 20000
  port: 80
spring:
  # thymeleaf 缓存开发时默认关闭
  thymeleaf:
    cache: false
  # 使用 jackson 转化日期格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 设置控制台输出彩色
  output:
    ansi:
      enabled: ALWAYS
  # 设置数据源
  datasource:
    # 使用 druid 连接池
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/bv?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driverClassName: com.mysql.jdbc.Driver
  # redis 缓存
  redis:
    host: localhost
    port: 6379
    password:
    # 连接超时时间（毫秒）
    timeout: 5000ms
    jedis:
      pool:
        # 最大空闲数
        max-idle: 8
        # 最小
        min-idle: 10
        # 最大连接数
        max-active: 100
        # 最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
  mvc:
      static-path-pattern: /**
  data:
    mongodb:
      host: localhost
      port: 27000
      database: chat
mybatis:
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  type-aliases-package: com.boot.bvserver.bean

# host 在本地测试可以设置为 localhost 或者本机 IP，在 Linux 服务器跑可换成服务器 IP
socketio:
  host: localhost
  port: 9099
  # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
  maxFramePayloadLength: 1048576
  # 设置http交互最大内容长度
  maxHttpContentLength: 1048576
  # socket连接数大小（如只监听一个端口boss线程组为1即可）
  bossCount: 1
  workCount: 100
  allowCustomRequests: true
  # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
  upgradeTimeout: 1000000
  # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
  pingTimeout: 6000000
  # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
  pingInterval: 25000